version: "3.1"

services:
  db:
    container_name: "PG"
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    networks:
      - network_postgres

networks:
  network_postgres:
    driver: bridge
